//! pdfium, bound directly.
//!
//! paddock rasterises PDF pages for the vision path and for the forensic
//! render-vs-scan comparison. That is SIX operations - open a document from
//! bytes, count its pages, read a page's size, render it to a bitmap - and
//! they used to come through `pdfium-render`.
//!
//! **Why we stopped.** That crate ships hand-written FFI declarations, one set
//! per pdfium vintage (`pdfium_7763`, `pdfium_7881`, ...), and with a STATIC link
//! those declarations are a vtable: every `FPDF_*` must resolve at link time, so
//! the library we build has to be a vintage the crate declares. Its newest was
//! 7881 while pdfium itself was at 8009 - meaning the version of a
//! memory-unsafe C++ parser we feed arbitrary user PDFs was set by a third
//! party's release cadence rather than by us. It had already left us four and a
//! half months behind once.
//!
//! Generating the FFI from the headers of the pdfium we actually build removes
//! the ceiling completely, and removes the whole class of "bindings vintage ≠
//! library vintage" bugs with it: the bindings are produced from the library.
//! The trade is that the unsafe boundary is ours now - for six calls, worth it;
//! if we ever wanted forms editing, annotations or text extraction, it would
//! not be. (Text extraction is sift's job; pdfium here is raster-only.)
//!
//! `ffi.rs` is generated by `bindgen` and COMMITTED - regenerate it in the same
//! commit that bumps `packs/pdfium/VERSION`, so the two can never disagree.
//! Committing rather than running bindgen from build.rs also keeps libclang off
//! the list of things you need to build paddock.
//!
//! **Threading.** pdfium's core is not reentrant and its global init must
//! happen exactly once. This crate does not serialise for you: the caller owns
//! one [`Pdfium`] for the process and takes its own lock. That is the same
//! contract `pdfium-render`'s `thread_safe` feature provided, moved to where
//! paddock already had a mutex.

#![allow(unsafe_code)]

/// Generated by bindgen from the headers of the pdfium in `packs/pdfium/`.
/// Do not edit - REGENERATE, in the same commit that moves the pin, with the
/// exact command in `regenerate.sh` beside this file. The lint allows are for
/// machine-written C names (`FPDFBitmap_BGRA`, `fpdf_document_t__`), which no
/// Rust style applies to.
#[allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    clippy::all,
    clippy::pedantic
)]
mod ffi;

use std::sync::Once;

/// A rendered page: interleaved RGB8, row-major, no padding.
pub struct Bitmap {
    pub rgb: Vec<u8>,
    pub width: u32,
    pub height: u32,
}

/// Process-wide pdfium. Construct exactly one; `FPDF_InitLibrary` runs on the
/// first call and never again.
pub struct Pdfium {
    _private: (),
}

static INIT: Once = Once::new();

impl Default for Pdfium {
    fn default() -> Self {
        Self::new()
    }
}

impl Pdfium {
    /// Initialise the statically linked pdfium. Cheap and idempotent.
    pub fn new() -> Self {
        // SAFETY: FPDF_InitLibrary takes no arguments and must be called once
        // before any other entry point; `Once` guarantees exactly that.
        INIT.call_once(|| unsafe { ffi::FPDF_InitLibrary() });
        Pdfium { _private: () }
    }

    /// Open a document held in memory. The bytes are not copied by pdfium, so
    /// they must outlive the returned document - which the lifetime enforces.
    pub fn load(&self, bytes: &[u8]) -> Result<Document<'_>, Error> {
        // SAFETY: pointer + length describe `bytes`, which outlives the
        // Document by the lifetime bound. A null password is "no password".
        let doc = unsafe {
            ffi::FPDF_LoadMemDocument64(bytes.as_ptr().cast(), bytes.len(), std::ptr::null())
        };
        if doc.is_null() {
            // SAFETY: no arguments; valid any time after init.
            return Err(Error::from_pdfium(
                unsafe { ffi::FPDF_GetLastError() } as u64
            ));
        }
        Ok(Document {
            handle: doc,
            _bytes: std::marker::PhantomData,
        })
    }
}

/// An open document. Closes itself on drop.
pub struct Document<'a> {
    handle: ffi::FPDF_DOCUMENT,
    _bytes: std::marker::PhantomData<&'a [u8]>,
}

impl Document<'_> {
    pub fn page_count(&self) -> usize {
        // SAFETY: handle is non-null and open for the life of `self`.
        let n = unsafe { ffi::FPDF_GetPageCount(self.handle) };
        n.max(0) as usize
    }

    /// Size of page `index` (0-based) in POINTS, as the page declares it.
    ///
    /// The `F` variants, deliberately. `FPDF_GetPageWidth`/`Height` are
    /// deprecated doubles that pdfium keeps only for compatibility; the float
    /// pair is what the current API returns and what accounts for page
    /// rotation the way callers expect.
    pub fn page_size(&self, index: usize) -> Option<(f32, f32)> {
        let page = self.page(index)?;
        Some((page.width(), page.height()))
    }

    fn page(&self, index: usize) -> Option<Page<'_>> {
        let idx = i32::try_from(index).ok()?;
        // SAFETY: handle is open; an out-of-range index returns null rather
        // than misbehaving, which is the check below.
        let p = unsafe { ffi::FPDF_LoadPage(self.handle, idx) };
        (!p.is_null()).then_some(Page {
            handle: p,
            _doc: std::marker::PhantomData,
        })
    }

    /// Render page `index` (0-based) at `width` x `height` pixels to RGB8.
    ///
    /// Matches what `pdfium-render`'s default `PdfRenderConfig` did, because
    /// the forensic render-vs-scan comparison diffs these pixels and a silent
    /// change of rendering would invalidate stored reports:
    ///   - a BGRA bitmap, cleared to opaque WHITE before drawing (a PDF page
    ///     is paper; without the clear the background is transparent black)
    ///   - `FPDF_ANNOT`, so annotations are drawn
    ///   - form field VALUES drawn on top via the form-fill environment. A
    ///     filled form renders blank without this, which for a document going
    ///     to a vision model loses exactly the content that matters.
    pub fn render(&self, index: usize, width: u32, height: u32) -> Result<Bitmap, Error> {
        let page = self.page(index).ok_or(Error::PageNotFound(index))?;
        let (w, h) = (width.max(1) as i32, height.max(1) as i32);

        // SAFETY: positive dimensions; BGRA is a valid format constant. Null
        // means the allocation failed (an enormous page, or OOM).
        let bmp = unsafe {
            ffi::FPDFBitmap_CreateEx(w, h, ffi::FPDFBitmap_BGRA as i32, std::ptr::null_mut(), 0)
        };
        if bmp.is_null() {
            return Err(Error::Render(index, "bitmap allocation failed".into()));
        }
        let _bmp = BitmapGuard(bmp);

        // SAFETY: bitmap is live and the rect is its full extent. 0xFFFFFFFF is
        // opaque white in pdfium's ARGB colour argument.
        unsafe { ffi::FPDFBitmap_FillRect(bmp, 0, 0, w, h, 0xFFFF_FFFF as ffi::FPDF_DWORD) };

        let flags = ffi::FPDF_ANNOT as i32;
        // SAFETY: bitmap and page are live; the destination rect is the whole
        // bitmap; rotation 0 = as the page declares itself.
        unsafe { ffi::FPDF_RenderPageBitmap(bmp, page.handle, 0, 0, w, h, 0, flags) };

        // Form field values, drawn over the page content exactly as pdfium's
        // own samples do. The environment is per-document and cheap; keeping it
        // scoped to the render means no handle outlives the document.
        let form = FormEnv::new(self.handle);
        if let Some(f) = form.handle() {
            // SAFETY: form handle came from this document; bitmap and page live.
            unsafe { ffi::FPDF_FFLDraw(f, bmp, page.handle, 0, 0, w, h, 0, flags) };
        }

        // SAFETY: bitmap is live; buffer is width*height*4 BGRA bytes with rows
        // `stride` apart, and stride may exceed width*4 (pdfium aligns rows).
        let buf = unsafe { ffi::FPDFBitmap_GetBuffer(bmp) };
        let stride = unsafe { ffi::FPDFBitmap_GetStride(bmp) } as usize;
        if buf.is_null() || stride < (w as usize) * 4 {
            return Err(Error::Render(index, "bitmap buffer unavailable".into()));
        }
        // SAFETY: pdfium owns `stride * height` bytes here, live until the
        // guard drops.
        let src = unsafe { std::slice::from_raw_parts(buf.cast::<u8>(), stride * h as usize) };
        Ok(Bitmap {
            rgb: bgra_to_rgb(src, w as usize, h as usize, stride),
            width: w as u32,
            height: h as u32,
        })
    }
}

impl Drop for Document<'_> {
    fn drop(&mut self) {
        // SAFETY: handle was opened by FPDF_LoadMemDocument64 and is closed once.
        unsafe { ffi::FPDF_CloseDocument(self.handle) };
    }
}

struct Page<'a> {
    handle: ffi::FPDF_PAGE,
    /// Ties the page to its document: pdfium invalidates every page handle
    /// when the document closes, so this must not outlive it.
    _doc: std::marker::PhantomData<&'a ()>,
}

impl Page<'_> {
    fn width(&self) -> f32 {
        // SAFETY: page is live.
        unsafe { ffi::FPDF_GetPageWidthF(self.handle) }
    }
    fn height(&self) -> f32 {
        // SAFETY: page is live.
        unsafe { ffi::FPDF_GetPageHeightF(self.handle) }
    }
}

impl Drop for Page<'_> {
    fn drop(&mut self) {
        // SAFETY: handle came from FPDF_LoadPage and is closed once.
        unsafe { ffi::FPDF_ClosePage(self.handle) };
    }
}

/// Closes the bitmap however the render exits.
struct BitmapGuard(ffi::FPDF_BITMAP);
impl Drop for BitmapGuard {
    fn drop(&mut self) {
        // SAFETY: created by FPDFBitmap_CreateEx, destroyed once.
        unsafe { ffi::FPDFBitmap_Destroy(self.0) };
    }
}

/// The form-fill environment, for drawing field values. Optional: a document
/// with no AcroForm still returns a handle, and one that fails to initialise
/// simply means no field values - never a failed render.
struct FormEnv(ffi::FPDF_FORMHANDLE);

impl FormEnv {
    fn new(doc: ffi::FPDF_DOCUMENT) -> Self {
        // The struct is all callbacks we do not supply (no interactivity, no
        // JavaScript); pdfium reads `version` and tolerates null function
        // pointers for a draw-only environment. Zeroed + version 2 is what
        // pdfium's own samples pass.
        let mut info: ffi::_FPDF_FORMFILLINFO = unsafe { std::mem::zeroed() };
        info.version = 2;
        // SAFETY: `info` outlives the call, and pdfium copies what it needs.
        // pdfium retains the pointer for the environment's life, so this leaks
        // the box deliberately - the environment is per-render and short-lived,
        // and a freed struct under pdfium would be a use-after-free.
        let boxed = Box::leak(Box::new(info));
        let h = unsafe { ffi::FPDFDOC_InitFormFillEnvironment(doc, boxed) };
        FormEnv(h)
    }
    fn handle(&self) -> Option<ffi::FPDF_FORMHANDLE> {
        (!self.0.is_null()).then_some(self.0)
    }
}

impl Drop for FormEnv {
    fn drop(&mut self) {
        if !self.0.is_null() {
            // SAFETY: handle came from InitFormFillEnvironment, exited once.
            unsafe { ffi::FPDFDOC_ExitFormFillEnvironment(self.0) };
        }
    }
}

/// BGRA rows (possibly padded to `stride`) to tightly packed RGB8.
///
/// Two things at once, which is why it is its own function with its own test:
/// dropping the alpha channel, and dropping the row padding pdfium adds to
/// align each scanline. Getting the stride wrong skews the image progressively
/// - the classic diagonal-smear bug - rather than failing.
fn bgra_to_rgb(src: &[u8], width: usize, height: usize, stride: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(width * height * 3);
    for y in 0..height {
        let row = &src[y * stride..y * stride + width * 4];
        for px in row.as_chunks::<4>().0 {
            out.push(px[2]); // R
            out.push(px[1]); // G
            out.push(px[0]); // B
        }
    }
    out
}

#[derive(Debug)]
pub enum Error {
    /// pdfium refused the document. Carries its own error word, mapped.
    Load(&'static str),
    PageNotFound(usize),
    Render(usize, String),
}

impl Error {
    fn from_pdfium(code: u64) -> Self {
        // FPDF_ERR_* from fpdfview.h. Worth mapping rather than printing a
        // number: "password required" and "corrupt file" send a user to very
        // different places.
        Error::Load(match code {
            1 => "unknown error",
            2 => "file not found or could not be opened",
            3 => "not a PDF, or corrupt",
            4 => "password required or incorrect",
            5 => "unsupported security scheme",
            6 => "page not found or content error",
            _ => "no error reported",
        })
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Load(m) => write!(f, "{m}"),
            Error::PageNotFound(i) => write!(f, "page {i} not found"),
            Error::Render(i, m) => write!(f, "page {i}: {m}"),
        }
    }
}

impl std::error::Error for Error {}

#[cfg(test)]
mod tests {
    use super::*;

    /// The stride/channel-order conversion, on a shape where every wrong answer
    /// looks different: 2x2, padded rows, and a distinct colour per pixel.
    #[test]
    fn bgra_to_rgb_drops_alpha_and_row_padding() {
        let stride = 12; // 2px * 4 bytes = 8, plus 4 bytes of padding
        let mut src = vec![0u8; stride * 2];
        // row 0: (10,20,30) then (40,50,60), stored B,G,R,A
        src[0..4].copy_from_slice(&[30, 20, 10, 255]);
        src[4..8].copy_from_slice(&[60, 50, 40, 255]);
        src[8..12].copy_from_slice(&[9, 9, 9, 9]); // padding, must not appear
        // row 1
        src[12..16].copy_from_slice(&[90, 80, 70, 255]);
        src[16..20].copy_from_slice(&[120, 110, 100, 255]);
        src[20..24].copy_from_slice(&[9, 9, 9, 9]);

        let rgb = bgra_to_rgb(&src, 2, 2, stride);
        assert_eq!(rgb, vec![10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]);
    }

    #[test]
    fn bgra_to_rgb_handles_unpadded_rows() {
        let src = [30, 20, 10, 255, 60, 50, 40, 255];
        assert_eq!(bgra_to_rgb(&src, 2, 1, 8), vec![10, 20, 30, 40, 50, 60]);
    }
}
