//! Host-side resamplers for the DeepEncoder's position tables - the pieces of
//! `deepencoder.py` that run once per (layer, geometry) rather than per token,
//! which is why they are Rust on the host and not kernels.
//!
//! Three resamples exist, and they use two different interpolators:
//!
//! * `get_abs_pos_sam` / `get_abs_pos` - **bicubic, antialias=True,
//!   align_corners=False** over a square channel grid. SAM's 64x64 table
//!   shrinks to 40x40 for a 640px crop; CLIP's 16x16 (CLS held out by the
//!   caller) shrinks to 10x10.
//! * `get_rel_pos` - **linear, no antialias** over rows. A global block's
//!   127-row table resamples to `2*side - 1` rows when the view is not 1024px
//!   (127 -> 79 at 640px). Windowed blocks never resample: q is always 14.
//!
//! The trap that makes this file fixture-gated rather than "obviously right":
//! torch's antialiased bicubic is not its plain bicubic with a prefilter
//! bolted on. The antialias path is the PIL-style separable convolution with
//! cubic coefficient **A = -0.5**, where plain `mode='bicubic'` uses
//! **A = -0.75** - so the two disagree even on UPSCALE, where no antialiasing
//! happens at all (measured: `up_3to5` aa vs plain differ). Every function
//! here is therefore pinned against outputs generated by the reference's
//! exact torch calls (our OCR oracle tool), not against an
//! idea of what bicubic means.
//!
//! Weights are computed and accumulated in f64 - these run a handful of times
//! per model load, and f64 keeps the fixture gate at 1e-9 instead of
//! wondering which side of 1e-6 is accumulation order.

/// PIL-class cubic filter, A = -0.5 - what torch's ANTIALIAS path uses for
/// every scale factor. (Plain `mode='bicubic'` is A = -0.75; the reference
/// never calls that.)
fn cubic_aa(x: f64) -> f64 {
    const A: f64 = -0.5;
    let x = x.abs();
    if x < 1.0 {
        ((A + 2.0) * x - (A + 3.0)) * x * x + 1.0
    } else if x < 2.0 {
        (((x - 5.0) * x + 8.0) * x - 4.0) * A
    } else {
        0.0
    }
}

/// One axis of the separable PIL/torch-aa resample: for output index `i`,
/// the contributing source range and normalized weights.
///
/// `support` is the filter's half-width (2.0 for cubic) scaled by the
/// downscale factor; on upscale the filter is not widened (`filterscale`
/// clamps at 1), which is exactly torch's `max(scale, 1.0)`.
fn axis_weights(s_in: usize, s_out: usize) -> Vec<(usize, Vec<f64>)> {
    let scale = s_in as f64 / s_out as f64;
    let filterscale = scale.max(1.0);
    let support = 2.0 * filterscale;
    (0..s_out)
        .map(|i| {
            let center = (i as f64 + 0.5) * scale;
            let xmin = ((center - support + 0.5).floor() as i64).max(0) as usize;
            let xmax = ((center + support + 0.5).floor() as i64).min(s_in as i64) as usize;
            let mut w: Vec<f64> = (xmin..xmax)
                .map(|j| cubic_aa((j as f64 - center + 0.5) / filterscale))
                .collect();
            let sum: f64 = w.iter().sum();
            if sum != 0.0 {
                for v in &mut w {
                    *v /= sum;
                }
            }
            (xmin, w)
        })
        .collect()
}

/// `get_abs_pos_sam` / `get_abs_pos`'s grid branch: `[src, src, ch]` row-major
/// -> `[dst, dst, ch]`, torch `mode='bicubic', antialias=True,
/// align_corners=False`. Separable: rows first, then columns.
pub fn bicubic_aa_grid(table: &[f64], src: usize, dst: usize, ch: usize) -> Vec<f64> {
    assert_eq!(table.len(), src * src * ch, "table is not [src, src, ch]");
    if src == dst {
        return table.to_vec();
    }
    let wx = axis_weights(src, dst);
    // horizontal pass: [src, dst, ch]
    let mut mid = vec![0.0f64; src * dst * ch];
    for y in 0..src {
        for (x, (x0, w)) in wx.iter().enumerate() {
            for c in 0..ch {
                let mut a = 0.0;
                for (dj, wj) in w.iter().enumerate() {
                    a += wj * table[(y * src + x0 + dj) * ch + c];
                }
                mid[(y * dst + x) * ch + c] = a;
            }
        }
    }
    // vertical pass: [dst, dst, ch]
    let wy = axis_weights(src, dst);
    let mut out = vec![0.0f64; dst * dst * ch];
    for (y, (y0, w)) in wy.iter().enumerate() {
        for x in 0..dst {
            for c in 0..ch {
                let mut a = 0.0;
                for (dj, wj) in w.iter().enumerate() {
                    a += wj * mid[((y0 + dj) * dst + x) * ch + c];
                }
                out[(y * dst + x) * ch + c] = a;
            }
        }
    }
    out
}

/// `get_rel_pos`'s resize: `[rows, ch]` -> `[dst, ch]`, torch `mode='linear'`
/// with the default `align_corners=False` - sample at `(i + 0.5)·scale - 0.5`,
/// edges clamped. No antialias: the reference passes none, and rel-pos tables
/// only ever SHRINK by ~1.6x where linear's own footprint is adequate.
pub fn linear_rows(table: &[f64], rows: usize, ch: usize, dst: usize) -> Vec<f64> {
    assert_eq!(table.len(), rows * ch, "table is not [rows, ch]");
    if rows == dst {
        return table.to_vec();
    }
    let scale = rows as f64 / dst as f64;
    let mut out = vec![0.0f64; dst * ch];
    for i in 0..dst {
        let x = ((i as f64 + 0.5) * scale - 0.5).max(0.0);
        let x0 = (x.floor() as usize).min(rows - 1);
        let x1 = (x0 + 1).min(rows - 1);
        let f = x - x0 as f64;
        for c in 0..ch {
            out[i * ch + c] = table[x0 * ch + c] * (1.0 - f) + table[x1 * ch + c] * f;
        }
    }
    out
}

/// `get_rel_pos` in full: resize the `[rows, ch]` relative table to
/// `2*side - 1` rows if needed, then index it absolutely into the
/// `[side, side, ch]` form the attention kernel reads -
/// `out[q][k] = resized[q - k + side - 1]`.
///
/// (The q/k coordinate scaling terms in the reference collapse for q == k,
/// which is the only case this family has: every attention here is
/// self-attention over one grid.)
pub fn rel_pos_table(table: &[f64], rows: usize, ch: usize, side: usize) -> Vec<f64> {
    let want = 2 * side - 1;
    let resized = linear_rows(table, rows, ch, want);
    let mut out = vec![0.0f64; side * side * ch];
    for q in 0..side {
        for k in 0..side {
            let r = q + side - 1 - k;
            out[(q * side + k) * ch..][..ch].copy_from_slice(&resized[r * ch..][..ch]);
        }
    }
    out
}

#[cfg(test)]
mod fixtures {
    include!("resample_fixtures.rs");
}

#[cfg(test)]
mod tests {
    use super::*;

    fn max_diff(a: &[f64], b: &[f64]) -> f64 {
        assert_eq!(a.len(), b.len());
        a.iter()
            .zip(b)
            .map(|(x, y)| (x - y).abs())
            .fold(0.0, f64::max)
    }

    /// The reference generator's LCG, so the big-shape checks regenerate their
    /// inputs instead of embedding 8k floats.
    fn lcg(n: usize) -> Vec<f64> {
        let mut s = 0x00c0_ffeeu64;
        (0..n)
            .map(|_| {
                s = s
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                ((s >> 40) as f64) / f64::from(1u32 << 23) - 1.0
            })
            .collect()
    }

    #[test]
    fn bicubic_aa_matches_torch_downscale() {
        let got = bicubic_aa_grid(fixtures::SAM_POS_6TO4_SRC, 6, 4, 3);
        assert!(max_diff(&got, fixtures::SAM_POS_6TO4_OUT) < 1e-9);
        let got = bicubic_aa_grid(fixtures::CLIP_POS_5TO3_SRC, 5, 3, 3);
        assert!(max_diff(&got, fixtures::CLIP_POS_5TO3_OUT) < 1e-9);
    }

    /// The real geometry: SAM's 64-grid table onto a 640px crop's 40-grid.
    #[test]
    fn bicubic_aa_matches_torch_at_the_sam_shape() {
        let got = bicubic_aa_grid(&lcg(64 * 64 * 2), 64, 40, 2);
        let sum: f64 = got.iter().sum();
        assert!(
            (sum - fixtures::SAM_POS_64TO40_SUM).abs() < 1e-7,
            "sum {sum}"
        );
        assert!(max_diff(&got[..8], fixtures::SAM_POS_64TO40_FIRST8) < 1e-9);
    }

    /// Upscale through the same path: torch's antialias bicubic keeps its
    /// A = -0.5 cubic on upscale (it does not fall back to plain bicubic's
    /// A = -0.75 - the two measurably differ). Never happens at the family's
    /// two pinned view sizes, but the branch exists, so it is pinned.
    #[test]
    fn bicubic_aa_matches_torch_upscale() {
        let got = bicubic_aa_grid(fixtures::UP_3TO5_SRC, 3, 5, 2);
        assert!(max_diff(&got, fixtures::UP_3TO5_AA) < 1e-9);
    }

    #[test]
    fn linear_matches_torch() {
        let got = linear_rows(fixtures::REL_9TO5_SRC, 9, 3, 5);
        assert!(max_diff(&got, fixtures::REL_9TO5_OUT) < 1e-9);
        // the real shape: a global block's 127-row table onto a 640px crop
        let got = linear_rows(&lcg(127 * 2), 127, 2, 79);
        let sum: f64 = got.iter().sum();
        assert!((sum - fixtures::REL_127TO79_SUM).abs() < 1e-9, "sum {sum}");
        assert!(max_diff(&got[..8], fixtures::REL_127TO79_FIRST8) < 1e-9);
    }

    /// The absolute indexing get_rel_pos does after its resize:
    /// `out[q][k] = table[q - k + side - 1]` - row 0 of the table is the
    /// most-negative relative offset (k far right of q).
    #[test]
    fn rel_pos_indexing_is_q_minus_k() {
        // identity-friendly table: rows = 2*side-1 already, ch=1, value = row
        let side = 4;
        let table: Vec<f64> = (0..2 * side - 1).map(|r| r as f64).collect();
        let out = rel_pos_table(&table, 2 * side - 1, 1, side);
        for q in 0..side {
            for k in 0..side {
                assert_eq!(out[q * side + k], (q + side - 1 - k) as f64, "q={q} k={k}");
            }
        }
        // diagonal (q == k) is always the center row
        for q in 0..side {
            assert_eq!(out[q * side + q], (side - 1) as f64);
        }
    }
}
